### 🧾 Título:
[Nombre de la tarea]
---
### 📌 Descripción:
[
  Descripción clara y concisa de lo que debe hacerse,
  incluyendo objetivos funcionales y técnicos,
]
---
### 📚 Librerías involucradas o como se involucra:
