# Deshabilitar seguridad básica (ya que estamos usando nuestra propia configuración)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/comoencasa_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.comoencasa_backend=TRACE


# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dundunbai123@gmail.com
spring.mail.password=dxki ebmp ozjn hlzg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# URL del frontend para construir el link de verificaci�n
frontend.url=http://localhost:3000

